"""empty message

Revision ID: 36f8af8e3c2
Revises: 4e8b62e6210
Create Date: 2019-03-08 19:06:23.492954

"""

# revision identifiers, used by Alembic.
revision = '36f8af8e3c2'
down_revision = '4e8b62e6210'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('client_id', sa.String(length=300), nullable=False),
    sa.Column('client_secret', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    ### end Alembic commands ###
