"""empty message

Revision ID: 3da621e581d
Revises: a7e331fea
Create Date: 2019-03-05 14:51:26.931395

"""

# revision identifiers, used by Alembic.
revision = '3da621e581d'
down_revision = 'a7e331fea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name', name='user_pkey')
    )
    op.drop_table('channel')
    ### end Alembic commands ###
