"""empty message

Revision ID: 47e16cd1d82
Revises: 3da621e581d
Create Date: 2019-03-05 14:52:11.092778

"""

# revision identifiers, used by Alembic.
revision = '47e16cd1d82'
down_revision = '3da621e581d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
