"""empty message

Revision ID: 4e8b62e6210
Revises: 47e16cd1d82
Create Date: 2019-03-05 14:52:35.285993

"""

# revision identifiers, used by Alembic.
revision = '4e8b62e6210'
down_revision = '47e16cd1d82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
