"""empty message

Revision ID: a7e331fea
Revises: 51e2c29ad95
Create Date: 2019-03-05 12:10:41.296651

"""

# revision identifiers, used by Alembic.
revision = 'a7e331fea'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
